sudo: required
services:
  - docker

before_install:
  - docker build -t vinhphanh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vinhphanh/docker-react npm run test -- --coverage